// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smzfslnuofnplafhlzin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtemZzbG51b2ZucGxhZmhsemluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTMzNzUsImV4cCI6MjA3MTE4OTM3NX0.3_w4MvqJQb0KjbM1ESwHpHUdk1rA71LBdd_26ZhPNpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});